### ISSUE TITLE
Wiring Diagram?

### ISSUE THREAD

**Issue by ca-equinoxe** [LeifBloomquist/OricKeyboardReader#1]
Hi @LeifBloomquist I'm really interested in getting this working - would you be able to clarify which pins on the Oric keyboard header go to which on the Arduino?

**Comment by ca-equinoxe** [comment]
Never mind - After taking more time to read the code I understand how the wiring is setup

**Comment by LeifBloomquist** [comment]
Glad to hear you found the info - I tried to document it reasonably well in the code.  Let me know if you need any help with it.
